# https://squidfunk.github.io/mkdocs-material/publishing-your-site/?h=deploy#with-github-actions
name: ci 
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Parsing
        run: python parser.py
      - name: Auto updating changes
        run: |
          git commit -am "Auto updating changes"
          git push
      - name: Deploying
        run: mkdocs gh-deploy --force
